src/objects/Station__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>経緯度</label>
        <scale>15</scale>
        <type>Location</type>
    </fields>
    <label>Station</label>
    <nameField>
        <label>駅名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GeocodingStationMapController.cls
public class GeocodingStationMapController extends GeocodingMapBaseController {
    public Double center_lat {get;set;}
    public Double center_lng {get;set;}

    protected override String searchOrder() {
        return 'DISTANCE(Location__c, GEOLOCATION(' + center_lat + ', ' + center_lng + '), \'km\')';
    }

    public GeocodingStationMapController() {
        super('Station__c');
        center_lat = 35.681391;
        center_lng = 139.766103;
    }
}