src/objects/Station__c.object
<CustomObject>
    <fields>
        <fullName>LineEXID__c</fullName>
        <externalId>true</externalId>
        <label>路線外部ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StationEXID__c</fullName>
        <externalId>true</externalId>
        <label>駅外部ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Station_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>路線</label>
        <referenceTo>Station_Line__c</referenceTo>
        <relationshipLabel>Stations</relationshipLabel>
        <relationshipName>Stations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Station</label>
    <nameField>
        <label>駅名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Station_Company__c.object
<CustomObject>
    <fields>
        <fullName>CompanyEXID__c</fullName>
        <externalId>true</externalId>
        <label>事業者外部ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Station Company</label>
    <nameField>
        <label>事業者名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Station Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Station_Line__c.object
<CustomObject>
    <fields>
        <fullName>CompanyEXID__c</fullName>
        <label>事業者外部ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LineEXID__c</fullName>
        <externalId>true</externalId>
        <label>路線外部ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Station_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>事業者</label>
        <referenceTo>Station_Company__c</referenceTo>
        <relationshipLabel>Station Lines</relationshipLabel>
        <relationshipName>Station_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Station Line</label>
    <nameField>
        <label>路線名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Station Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StationTriggerTest.cls
@isTest
private class StationTriggerTest {
    static testMethod void commonTest() {
        Test.startTest();
        Station_Company__c c = new Station_Company__c(
            Name = 'c',
            CompanyEXID__c = 1
        );
        insert c;
        Station_Line__c l = new Station_Line__c(
            Name = 'l',
            CompanyEXID__c = 1,
            LineEXID__c = 1
        );
        insert l;
        Station__c s = new Station__c(
            Name = 'test',
            StationEXID__c = 1,
            LineEXID__c = 1
        );
        insert s;
        
        Test.stopTest();
    }
}